[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Solidity compiler configuration
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

# Network configuration for deployments
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
